baseURL = "http://example.org/"
languageCode = "en-us"
theme = "sada-template"
staticDir= "static"
publishDir= "docs"

[params]
    title = "Nikolay Ganev"
    author = "Nikolay Ganev"
    description = "System Engineer"
    copyright = ""
    copyright_link = ""

    # Profile section
    [params.profile]
        name = "Nikolay Ganev"
        photo = "nikolayganev.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        class = "fab"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/nikoganev/"
        title = "LinkedIn"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/nikoganev"
        title = "GitHub"
			

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Biotechnology"
        college = "University of Vic"
        dates = "2012 - 2015"

        [[params.education.list]]
        degree = "Front End and Mobile App Developer"
        college = "Bootcamp - Barcelona Activa"
        dates = "2016 - 2016"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "Spanish"
        level = "Fluent"

        [[params.language.list]]
        language = "Catalan"
        level = "Fluent"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Travelling"
		
		[[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Stockmarket"

        [[params.hobbies.list]]
        interest = "Fitness/Workingout"

    [params.aboutme]
        description = "Front end and Back end Certified Developer. Having background in building mobile applications using jQuery, Cordova Frameworks and other technologies. Currently working as a System Engineer in Fintech industry. In my free time I'm building websites for small businesses and helping them get more clients using Hubspot Inbound for lead generation. I'm certified in Hubspot Marketing owning 5 certifications in Sales, Content Marketing, Inbound Strategies, Design and Email Marketing. "

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "System Engineer"
        dates = "2018 - *Present*"
		link = "www.finos.org"
        company = "FINOS - Fintech Open Source Foundation"

        [[params.jobs.list]]
        position = "System Engineer"
        dates = "2017 - 2018"
		link = "#"
        company = "Symphony Foundation"
        
        [[params.jobs.list]]
        position = "Front End Developer"
        dates = "2017 - 2017"
        link = "#"
        company = "Symphony Foundation"

        [[params.jobs.list]]
        position = "Mobile App Developer"
        dates = "2016 - 2016"
        link = "#"
        company = "Self employed"

        [[params.jobs.list]]
        position = "Video Editor Youtube"
        dates = "2014-2016"
        link = "#"
        company = "Youtube Creator"

        [[params.jobs.list]]
        position = "Ecommerce book seller at Amazon"
        dates = "2016-2016"
        link = "#"
        company = "Amazon Seller"

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Projects"

        [[params.projects.list]]
        title = "Building website for agency"
        url = "#"
        description = "Building a website for a local tax agency, creating social accounts and building their internet presence using tools such as Google Business and Google Search Console. You can check their website at: https://gestoriasbaratas.es/"
		
		[[params.projects.list]]
        title = "Personal Website"
        url = "#"
        description = "Build my personal website where you can find all the services I'm oferring. I have used the Hugo templates but also customized it on my taste. You can check the website at: https://nikovenag.com/"

    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]
        skill = "Skill 1, Skill 2"
        skillrating = 95 # out of 100
                
        [[params.skills.list]]
        skill = "Skill 3"
        skillrating = 90
		
        [[params.skills.list]]
        skill = "Skill 4"
        skillrating = 80
